[package]
name = "maps"
description = "Inspect, compare and align multiple grid maps in an intuitive & fast GUI"
authors = ["Michael Grupp"]
license = "Apache-2.0"
repository = "https://www.github.com/MichaelGrupp/maps"
homepage = "https://www.github.com/MichaelGrupp/maps"
categories = ["science::robotics", "visualization", "gui", "multimedia::images"]
keywords = ["map", "navigation", "SLAM", "ROS", "egui"]
version = "1.2.0"
edition = "2021"
readme = "README.md"
build = "build.rs"
exclude = ["data/**/", "test/snapshots"]

[features]
# kittest snapshot diff tests are enabled by default (see tests/).
# Disable when testing on a runner without wgpu support.
kittest_snapshots = []
default = ["kittest_snapshots"]

[build-dependencies]
built = { version = "0.7.5", features = ["git2"] }

[profile.kittest]
# kittests would be a bit too slow without optimizations.
inherits = "release"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
confy = "0.6.1"
eframe = {version = "0.31.0", features = ["wgpu"]}
egui_extras = { version = "0.31.0", features = ["all_loaders", "serde"] }
egui_dnd = "0.12.0"
egui-file-dialog = "0.9.0"
egui_kittest = { version = "0.31.0", features = ["wgpu", "snapshot", "eframe"] }
egui_tiles = "0.12.0"
env_logger = "0.11.5"
fast_image_resize = { version = "5.1.1", features = ["image"] }
lazy_static = "1.5.0"
image = { version = "0.25.5", features = ["jpeg", "png", "pnm"] }
imageproc = "0.25.0"
log = "0.4.22 "
serde = "1.0"
serde_yaml_ng = "0.10.0"
strum = "0.26.3"
strum_macros = "0.26.3"
toml = "0.8.19"
uuid = { version = "1.11.0", features = ["v4"] }

# Native only:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.5"

# Web only:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
web-sys = "0.3.70"
console_error_panic_hook = "0.1.7"  # wasm error messages in the browser console
rfd = "0.15.2"

[profile.release]
opt-level = 2 # fast and small wasm
