[package]
name = "maps"
description = "Inspect, compare and align multiple grid maps in an intuitive & fast GUI"
authors = ["Michael Grupp"]
license = "Apache-2.0"
repository = "https://www.github.com/MichaelGrupp/maps"
homepage = "https://www.github.com/MichaelGrupp/maps"
categories = ["science:robotics", "visualization", "gui", "multimedia::images"]
keywords = [
  "map", "grid", "occupancy",
  "SLAM", "navigation", "robotics", 
  "ROS", "visualization", "egui"
]
version = "1.0.0"
edition = "2021"
readme = "README.md"
build = "build.rs"

[build-dependencies]
built = { version = "0.7.5", features = ["git2"] }

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
confy = "0.6.1"
eframe = {version = "0.30.0", features = ["wgpu"]}
egui_extras = { version = "0.30.0", features = ["all_loaders"] }
egui-file-dialog = "0.8.0"
egui_tiles = "0.11.0"
env_logger = "0.11.5"
fast_image_resize = { version = "5.1.1", features = ["image"] }
image = { version = "0.25.5", features = ["jpeg", "png", "pnm"] }
imageproc = "0.25.0"
log = "0.4.22 "
serde = "1.0"
serde_yaml_ng = "0.10.0"
strum = "0.26.3"
strum_macros = "0.26.3"
toml = "0.8.19"
uuid = { version = "1.11.0", features = ["v4"] }
