[package]
name = "rosmaps"
authors = ["Michael Grupp"]
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
eframe = "0.29.1"
egui_extras = { version = "0.29.1", features = ["all_loaders"] }
env_logger = "0.11.5"
image = { version = "0.25.5", features = ["jpeg", "png", "pnm"] }
log = "0.4.22 "
nalgebra = "0.33.2"
serde = "1.0"
serde_yml = "0.0.12"
